
import com.github.kwhat.jnativehook.keyboard.NativeKeyListener;
import javax.swing.ButtonModel;

import GestionMacro.Hook;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Antoni
 */
public class Interface extends javax.swing.JFrame {
    private int delay;
    private int activationCode = 50;
    private final Hook hook;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        hook = new Hook();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grMacro = new javax.swing.ButtonGroup();
        labTitre = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        radioNothing = new javax.swing.JRadioButton();
        radioLR = new javax.swing.JRadioButton();
        radioAuto = new javax.swing.JRadioButton();
        sliderAuto = new javax.swing.JSlider();
        butValide = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        labelDelay = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        butActivation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Macro");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTitre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labTitre.setText("Type de macro :");
        getContentPane().add(labTitre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 340, -1));

        grMacro.add(radioNothing);
        radioNothing.setSelected(true);
        radioNothing.setText("Nothing");
        getContentPane().add(radioNothing, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        grMacro.add(radioLR);
        radioLR.setText("Left/Right click");
        getContentPane().add(radioLR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        radioLR.setActionCommand("leftright");

        grMacro.add(radioAuto);
        radioAuto.setText("Auto click");
        getContentPane().add(radioAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        radioAuto.setActionCommand("autoclick");

        sliderAuto.setMinimum(1);
        sliderAuto.setPreferredSize(new java.awt.Dimension(100, 15));
        sliderAuto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAutoStateChanged(evt);
            }
        });
        getContentPane().add(sliderAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 90, 20));

        butValide.setText("validate");
        butValide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValideActionPerformed(evt);
            }
        });
        getContentPane().add(butValide, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 9));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Macro activation :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 340, 9));

        labelDelay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDelay.setText("0.5s btw click");
        getContentPane().add(labelDelay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 340, 9));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 131, 10, 40));

        butActivation.setText("2");
        butActivation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butActivationActionPerformed(evt);
            }
        });
        butActivation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                butActivationKeyPressed(evt);
            }
        });
        getContentPane().add(butActivation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderAutoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAutoStateChanged
        delay = (sliderAuto.getValue())*10;
        hook.setDelay(delay);
        labelDelay.setText((float)(sliderAuto.getValue())/100 + "s btw click");
    }//GEN-LAST:event_sliderAutoStateChanged

    private void butActivationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_butActivationKeyPressed
        if (evt.getKeyCode() != 27){
            activationCode = evt.getKeyCode();
            hook.setActivationCode(activationCode);
        }
        String keyName = java.awt.event.KeyEvent.getKeyText(activationCode);
        butActivation.setText(keyName);
        this.requestFocusInWindow();
    }//GEN-LAST:event_butActivationKeyPressed

    private void butValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValideActionPerformed
        String action = grMacro.getSelection().getActionCommand();
        if (action == null) {
            labTitre.setText("Type de macro :");
        } else {
            labTitre.setText("Type de macro : " + action);
        }
        hook.setMacro(action);
        
    }//GEN-LAST:event_butValideActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        hook.formWindowClosing(evt);
    }//GEN-LAST:event_formWindowClosing

    private void butActivationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butActivationActionPerformed
        butActivation.setText("...");
    }//GEN-LAST:event_butActivationActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butActivation;
    private javax.swing.JButton butValide;
    private javax.swing.ButtonGroup grMacro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private java.awt.Label labTitre;
    private javax.swing.JLabel labelDelay;
    private javax.swing.JRadioButton radioAuto;
    private javax.swing.JRadioButton radioLR;
    private javax.swing.JRadioButton radioNothing;
    private javax.swing.JSlider sliderAuto;
    // End of variables declaration//GEN-END:variables
}
